Repository YAPP-16th/Team_Android_2_Client, pull requests merged in 2020-05, with the labels that each got.

#35 [PR-35] 팀 리스트, 팀 찾기 화면 작업 및 서체/테마 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/data/MainRepositoryImpl.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/MyTeam.kt
  app/src/main/java/kr/yapp/teamplay/domain/repository/MainRepository.kt
  app/src/main/java/kr/yapp/teamplay/presentation/MainViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/MyTeamAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/MyTeamSelectActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/MyTeamSelectViewModel.kt
  app/src/main/java/kr/yapp/teamplay/util/IntExtension.kt
  app/src/main/res/drawable-hdpi/icon_android_logo.png
  app/src/main/res/drawable-mdpi/icon_android_logo.png
  app/src/main/res/drawable-xhdpi/icon_android_logo.png
  app/src/main/res/drawable-xxhdpi/icon_android_logo.png
  app/src/main/res/drawable-xxxhdpi/icon_android_logo.png
  app/src/main/res/font/sf_pro_bold.otf
  app/src/main/res/font/sf_pro_light.otf
  app/src/main/res/font/sf_pro_regular.otf
  app/src/main/res/font/sf_pro_thin.otf
  app/src/main/res/layout/activity_select_my_team.xml
  app/src/main/res/layout/rv_item_my_team.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: andorid

#36 Feature/onboarding signin signup
  app/src/main/java/kr/yapp/teamplay/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupNicknameFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/util/SingleLiveEvent.kt
  app/src/main/res/drawable-hdpi/background.png
  app/src/main/res/drawable-hdpi/logotype.png
  app/src/main/res/drawable-mdpi/background.png
  app/src/main/res/drawable-mdpi/logotype.png
  app/src/main/res/drawable-xhdpi/background.png
  app/src/main/res/drawable-xhdpi/logotype.png
  app/src/main/res/drawable-xxhdpi/background.png
  app/src/main/res/drawable-xxhdpi/logotype.png
  app/src/main/res/drawable-xxxhdpi/background.png
  app/src/main/res/drawable-xxxhdpi/logotype.png
  app/src/main/res/drawable/ic_google_plus.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/onboarding_roundbutton.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/fragment_signin_email.xml
  app/src/main/res/layout/fragment_signin_password.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_nickname.xml
  app/src/main/res/layout/fragment_signup_password.xml
  app/src/main/res/transition/enter_from_right.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: andorid

#38 [PR-38] 팀 생성 화면 UI 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/domain/entity/MyTeam.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/MyTeamAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/MyTeamSelectActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/create/TeamCreateActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/myteam/create/TeamCreateViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupActivity.kt
  app/src/main/res/drawable-hdpi/background.webp
  app/src/main/res/drawable-hdpi/bg.png
  app/src/main/res/drawable-hdpi/bg.webp
  app/src/main/res/drawable-hdpi/gradation_box.webp
  app/src/main/res/drawable-hdpi/img_team_create_thumbnail.webp
  app/src/main/res/drawable-hdpi/logotype.png
  app/src/main/res/drawable-mdpi/background.webp
  app/src/main/res/drawable-mdpi/bg.png
  app/src/main/res/drawable-mdpi/bg.webp
  app/src/main/res/drawable-mdpi/gradation_box.webp
  app/src/main/res/drawable-mdpi/img_team_create_thumbnail.webp
  app/src/main/res/drawable-mdpi/logotype.png
  app/src/main/res/drawable-xhdpi/background.webp
  app/src/main/res/drawable-xhdpi/bg.png
  app/src/main/res/drawable-xhdpi/bg.webp
  app/src/main/res/drawable-xhdpi/gradation_box.webp
  app/src/main/res/drawable-xhdpi/img_team_create_thumbnail.webp
  app/src/main/res/drawable-xhdpi/logotype.png
  app/src/main/res/drawable-xxhdpi/background.webp
  app/src/main/res/drawable-xxhdpi/bg.png
  app/src/main/res/drawable-xxhdpi/bg.webp
  app/src/main/res/drawable-xxhdpi/gradation_box.webp
  app/src/main/res/drawable-xxhdpi/img_team_create_thumbnail.webp
  app/src/main/res/drawable-xxhdpi/logotype.png
  app/src/main/res/drawable-xxxhdpi/background.webp
  app/src/main/res/drawable-xxxhdpi/bg.png
  app/src/main/res/drawable-xxxhdpi/bg.webp
  app/src/main/res/drawable-xxxhdpi/gradation_box.webp
  app/src/main/res/drawable-xxxhdpi/img_team_create_thumbnail.webp
  app/src/main/res/drawable-xxxhdpi/logotype.png
  app/src/main/res/drawable/bg_basketball_red_round8_stroke.xml
  app/src/main/res/drawable/bg_basketballred2_gradient.xml
  app/src/main/res/drawable/bg_gray_round8_solid.xml
  app/src/main/res/drawable/ic_arrow_down_red.xml
  app/src/main/res/drawable/ic_arrow_left_white.xml
  app/src/main/res/drawable/ic_basketball.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/activity_select_my_team.xml
  app/src/main/res/layout/activity_team_create.xml
  app/src/main/res/layout/item_team_create_question.xml
  app/src/main/res/layout/rv_item_my_team.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/team_create_menu.xml
Labels: Feature, andorid

#42 [PR-39] MatchList, MatchDetail 뷰 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/domain/entity/DetailMatch.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/MatchList.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_detail/MatchDetailActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_detail/MatchDetailViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_schedule/MatchScheduleActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_schedule/MatchScheduleInnerAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_schedule/MatchScheduleOuterAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_schedule/MatchScheduleViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupNicknameFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupPasswordFragment.kt
  app/src/main/res/drawable-hdpi/logotype.png
  app/src/main/res/drawable-mdpi/logotype.png
  app/src/main/res/drawable-xhdpi/logotype.png
  app/src/main/res/drawable-xxhdpi/logotype.png
  app/src/main/res/drawable-xxxhdpi/logotype.png
  app/src/main/res/drawable/match_list_searchbox.xml
  app/src/main/res/layout/activity_match_detail.xml
  app/src/main/res/layout/activity_match_list.xml
  app/src/main/res/layout/activity_match_schedule.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_signin_email.xml
  app/src/main/res/layout/fragment_signin_password.xml
  app/src/main/res/layout/fragment_signup_email.xml
  app/src/main/res/layout/fragment_signup_nickname.xml
  app/src/main/res/layout/fragment_signup_password.xml
  app/src/main/res/layout/item_match_list.xml
  app/src/main/res/layout/item_match_schedule_host_guest.xml
  app/src/main/res/layout/item_match_schedule_reserved.xml
  app/src/main/res/layout/item_match_schedule_subtitle.xml
  app/src/main/res/values/strings.xml
Labels: Feature, andorid

#45 [PR-45] MatchList, MatchDetail 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/data/RetrofitManager.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchList.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchListResponse.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchRepositoryImpl.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchService.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchStyle.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/MatchInfo.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/MatchList.kt
  app/src/main/java/kr/yapp/teamplay/domain/repository/MatchRepository.kt
  app/src/main/java/kr/yapp/teamplay/domain/usecase/GetMatchDetail.kt
  app/src/main/java/kr/yapp/teamplay/domain/usecase/GetMatchList.kt
  app/src/main/java/kr/yapp/teamplay/domain/usecase/GetMatchSchedule.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_detail/MatchDetailActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_detail/MatchDetailViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/match_list/MatchListViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupNicknameFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupViewModel.kt
  app/src/main/res/drawable/match_list_searchbox.xml
  app/src/main/res/drawable/shape_search_box.xml
  app/src/main/res/layout/activity_match_detail.xml
  app/src/main/res/layout/activity_match_list.xml
  app/src/main/res/layout/activity_match_search.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_match_list.xml
  app/src/main/res/values/strings.xml
Labels: Feature, bug, 안드로이드

#46 [PR-46]Signin, Signup 컨플릭트 수정
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupNicknameFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupPasswordFragment.kt
Labels: Hotfix

#48 [PR-48] Splash 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninEmailFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninPasswordFragment.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SigninViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/splash/SplashActivity.kt
  app/src/main/res/anim/logo_fade_in.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 안드로이드

#50 [PR-50] Hotfix / Login, Signup
  app/src/main/java/kr/yapp/teamplay/data/auth/signin/SigninResponse.kt
  app/src/main/java/kr/yapp/teamplay/data/auth/signup/SignupResponse.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/AccessToken.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/UserInfo.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/signin/SignupViewModel.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/item_search_active_label.xml
  app/src/main/res/drawable/item_search_deactive_label.xml
  app/src/main/res/layout/activity_match_search.xml
  app/src/main/res/values/strings.xml
Labels: Hotfix, bug

#49 [PR-49] 필터화면, 가입 신청 화면 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/yapp/teamplay/data/RetrofitManager.kt
  app/src/main/java/kr/yapp/teamplay/data/club/ClubApi.kt
  app/src/main/java/kr/yapp/teamplay/data/club/ClubRepositoryImpl.kt
  app/src/main/java/kr/yapp/teamplay/data/club/TeamCharacterResponse.kt
  app/src/main/java/kr/yapp/teamplay/data/match/MatchRepositoryImpl.kt
  app/src/main/java/kr/yapp/teamplay/domain/entity/TeamCharacter.kt
  app/src/main/java/kr/yapp/teamplay/domain/repository/ClubRepository.kt
  app/src/main/java/kr/yapp/teamplay/presentation/filter/TeamCharacterAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/filter/TeamSearchFilterActivity.kt
  app/src/main/java/kr/yapp/teamplay/presentation/filter/TeamSearchFilterViewModel.kt
  app/src/main/java/kr/yapp/teamplay/presentation/search/TeamListAdapter.kt
  app/src/main/java/kr/yapp/teamplay/presentation/search/TeamSearchActivity.kt
  app/src/main/res/drawable/icon_search.xml
  app/src/main/res/layout/activity_filer_team_search.xml
  app/src/main/res/layout/item_team_list.xml
  app/src/main/res/layout/item_team_list_header.xml
  app/src/main/res/layout/rv_item_character.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/team_create_menu.xml
Labels: Feature, 안드로이드
